---
platforms:
  - name: postfix-nullclient-ubuntu-24
    image: "geerlingguy/docker-ubuntu2404-ansible"
    groups:
      - ubuntu
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    override_command: false
    pre_build_image: true

  - name: postfix-nullclient-ubuntu-22
    image: "geerlingguy/docker-ubuntu2204-ansible"
    groups:
      - ubuntu
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    override_command: false
    pre_build_image: true

  - name: postfix-nullclient-ubuntu-20
    image: "geerlingguy/docker-ubuntu2004-ansible"
    groups:
      - ubuntu
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    override_command: false
    pre_build_image: true

  - name: postfix-nullclient-debian-12
    image: "geerlingguy/docker-debian12-ansible"
    groups:
      - debian
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    override_command: false
    pre_build_image: true

  - name: postfix-nullclient-debian-11
    image: "geerlingguy/docker-debian11-ansible"
    groups:
      - debian
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    override_command: false
    pre_build_image: true
