- hosts: postfix-nullclient-arch
  gather_facts: false
  tasks:
    - name: Install python3 # noqa no-changed-when
      raw: pacman -Sy python --noconfirm

- hosts: "ubuntu:debian"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
