name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: "CI"
    runs-on: ubuntu-latest
    strategy:
        matrix:
            job:
                - molecule-ansible8
                - molecule-ansible9
                - lint
    steps:
      - name: Check out codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Set up pip
        run: pip3 install --upgrade pip

      - name: Install tox
        run: sudo apt update && sudo apt -y install tox

      - name: Run Tox
        run: tox -e ${{ matrix.job }}
